import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { TextField } from "@mui/material";
import { useState, useEffect } from "react";
import SwipeableEdgeDrawer from "../components/Drawer";
export default function Home() {
    
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main >
                
                <SwipeableEdgeDrawer></SwipeableEdgeDrawer>
            </main>

           
        </div>
    );
}
